name: bestdroid
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+20
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  get: ^4.7.2
  get_storage: ^2.1.1
  intl_utils: ^2.8.11
  local_auth: ^2.3.0
  permission_handler: ^12.0.1
  flutter_svg: ^2.2.0
  dropdown_button2: ^2.3.9
  change_app_package_name: ^1.5.0
  sms_sender:
    path: packages/sms_sender

  #  cached_network_image: ^3.2.3
  #  flutter_sms:
  #    git:
  #      url: https://github.com/fluttercommunity/flutter_sms.git
  #      ref: master

  #  flutter_sms:
  #    path: packages/flutter_sms


  cupertino_icons: ^1.0.8
#  package_info_plus: ^8.3.1


dependency_overrides:
  intl: ^0.19.0
#  flutter_sms:
#    path: packages/flutter_sms

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


  flutter_launcher_icons: ^0.14.4
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/assets/logo/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/assets/logo/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/assets/logo/icon.png"
    #    flutter pub run flutter_launcher_icons

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/fonts/
    - lib/assets/logo/
    - lib/assets/png/
    - lib/assets/img/
    - lib/assets/svg/


  fonts:
    - family: IRANSans
      fonts:
        - asset: lib/assets/fonts/IRANSansWeb_Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/IRANSansWeb_Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/IRANSansWeb_Light.ttf
          weight: 300

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
